//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Register.
        /// </summary>
        internal static string AccountController_Register_Register_Error {
            get {
                return ResourceManager.GetString("AccountController_Register_Register_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argee Condition.
        /// </summary>
        internal static string AccountController_Register_You_Must_Argee_Condition {
            get {
                return ResourceManager.GetString("AccountController_Register_You_Must_Argee_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bài viết nào ở đây!.
        /// </summary>
        internal static string BlogCategory_Not_Found {
            get {
                return ResourceManager.GetString("BlogCategory_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        internal static string BlogPost_Text {
            get {
                return ResourceManager.GetString("BlogPost_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Breadcrumb_Home_Text {
            get {
                return ResourceManager.GetString("Breadcrumb_Home_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string Button_Search_Name {
            get {
                return ResourceManager.GetString("Button_Search_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string Categories_Text {
            get {
                return ResourceManager.GetString("Categories_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình luận.
        /// </summary>
        internal static string Comments_Text {
            get {
                return ResourceManager.GetString("Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình luận bài viết.
        /// </summary>
        internal static string Comment_Text {
            get {
                return ResourceManager.GetString("Comment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sân bay.
        /// </summary>
        internal static string Filter_Category {
            get {
                return ResourceManager.GetString("Filter_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string Filter_Price {
            get {
                return ResourceManager.GetString("Filter_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dữ liệu liên quan đến từ khóa.
        /// </summary>
        internal static string Item_For_Keyword_Text {
            get {
                return ResourceManager.GetString("Item_For_Keyword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xu hướng.
        /// </summary>
        internal static string Label_Trends_Text {
            get {
                return ResourceManager.GetString("Label_Trends_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết mới.
        /// </summary>
        internal static string LatestPosts_Text {
            get {
                return ResourceManager.GetString("LatestPosts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem nhiều nhất.
        /// </summary>
        internal static string Mostviewed_Text {
            get {
                return ResourceManager.GetString("Mostviewed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email, nhận ngay tin khuyến mãi.
        /// </summary>
        internal static string NewsLetterButton_PlaceHolder {
            get {
                return ResourceManager.GetString("NewsLetterButton_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string NewsLetterButton_Text {
            get {
                return ResourceManager.GetString("NewsLetterButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ồ... Email này đã được đăng ký, bạn kiểm tra lại.
        /// </summary>
        internal static string NewsLetterEmailDuplicated_Text {
            get {
                return ResourceManager.GetString("NewsLetterEmailDuplicated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng, bạn đã đăng ký email nhận bản tin thành công!.
        /// </summary>
        internal static string NewsLetterSuccessful_Text {
            get {
                return ResourceManager.GetString("NewsLetterSuccessful_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next_Button {
            get {
                return ResourceManager.GetString("Next_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ồ... Không tìm thấy gợi ý tương ứng!.
        /// </summary>
        internal static string NoSuggestionNotice_Text {
            get {
                return ResourceManager.GetString("NoSuggestionNotice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục khác.
        /// </summary>
        internal static string OtherCategories_Text {
            get {
                return ResourceManager.GetString("OtherCategories_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Gallery.
        /// </summary>
        internal static string Our_Gallery_Text {
            get {
                return ResourceManager.GetString("Our_Gallery_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string Page_Text {
            get {
                return ResourceManager.GetString("Page_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề phổ biến.
        /// </summary>
        internal static string PopularTags_Text {
            get {
                return ResourceManager.GetString("PopularTags_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bởi.
        /// </summary>
        internal static string PostedBy_Text {
            get {
                return ResourceManager.GetString("PostedBy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo sân bay.
        /// </summary>
        internal static string Prefix_AirportAdvertising {
            get {
                return ResourceManager.GetString("Prefix_AirportAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string Price_Text {
            get {
                return ResourceManager.GetString("Price_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string Product_Text {
            get {
                return ResourceManager.GetString("Product_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        internal static string Read_More_Text {
            get {
                return ResourceManager.GetString("Read_More_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm liên quan.
        /// </summary>
        internal static string RelatedProduct_Text {
            get {
                return ResourceManager.GetString("RelatedProduct_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cùng danh mục.
        /// </summary>
        internal static string SameCategory_Text {
            get {
                return ResourceManager.GetString("SameCategory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string Seach_Button_Text {
            get {
                return ResourceManager.GetString("Seach_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gõ từ khóa.
        /// </summary>
        internal static string Search_PlaceHolder {
            get {
                return ResourceManager.GetString("Search_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy kết quả tương ứng với từ khóa.
        /// </summary>
        internal static string Search_Results_Not_Found {
            get {
                return ResourceManager.GetString("Search_Results_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm.
        /// </summary>
        internal static string Search_Results_Text {
            get {
                return ResourceManager.GetString("Search_Results_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo bài viết.
        /// </summary>
        internal static string Suggest_ByBlogPost {
            get {
                return ResourceManager.GetString("Suggest_ByBlogPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo trang tĩnh.
        /// </summary>
        internal static string Suggest_ByPage {
            get {
                return ResourceManager.GetString("Suggest_ByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo trang.
        /// </summary>
        internal static string Suggest_ByPages {
            get {
                return ResourceManager.GetString("Suggest_ByPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo sản phẩm.
        /// </summary>
        internal static string Suggest_ByProduct {
            get {
                return ResourceManager.GetString("Suggest_ByProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo xu hướng.
        /// </summary>
        internal static string Suggest_ByTrends {
            get {
                return ResourceManager.GetString("Suggest_ByTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        internal static string ViewAll_Text {
            get {
                return ResourceManager.GetString("ViewAll_Text", resourceCulture);
            }
        }
    }
}
